#= 
    This code was generated by heta-compiler 0.11.1
=#

(function()

### create default constants
nameless_constants_num_ = NamedTuple{(
  :threeshold,:k1,:k2,:k3,:k4,:k5,:k6,
)}(Float64[
  1.5,0.001,0.001,0.001,0.001,0.001,0.001,
])
### create static ids
nameless_statics_id_ = (
    :c1,
)

### create default observables
nameless_records_output_ = NamedTuple{(
  :c1,:s1,:r1,:s2,:r2,:s3,:r3,:s4,:r4,:s5,:r5,:s6,:r6,
)}(Bool[
  false,true,false,true,false,true,false,true,false,true,false,true,false,
])

### create default events
nameless_events_active_ = NamedTuple{(
  :sw1,:sw2,:sw3,:sw4,:sw5,:sw6,
)}(Bool[
  true,true,true,true,true,true,
])

### vector of non-steady-state
nameless_dynamic_nonss_ = NamedTuple{(
  :s1,:s2,:s3,:s4,:s5,:s6,
)}(Bool[
  true,true,true,true,true,true,
])

### initialization of ODE variables and Records
function nameless_init_func_!(__u0__, __p0__, __constants__)
    # Heta initialize
    t = 0.0 # initial time
    s1 = 1e+0
    c1 = 1e+0
    r1 = __constants__[2] * s1 * c1
    s2 = 1e+0
    r2 = __constants__[3] * s2 * c1
    s3 = 1e+0
    r3 = __constants__[4] * s3 * c1
    s4 = 1e+0
    r4 = __constants__[5] * s4 * c1
    s5 = 1e+0
    r5 = __constants__[6] * s5 * c1
    s6 = 1e+0
    r6 = __constants__[7] * s6 * c1
    
    # save results
    __u0__ .= (
        s1 * c1,
        s2 * c1,
        s3 * c1,
        s4 * c1,
        s5 * c1,
        s6 * c1,
    )

    __p0__ .= (
        c1,
    )

    return nothing
end

### calculate RHS of ODE
function nameless_ode_func_(__du__, __u__, __p__, t)
    (c1,) = __p__.x[1]
    __constants__ = __p__.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __u__ 

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    r4 = __constants__[5] * s4 * c1
    s5 = s5_ / c1
    r5 = __constants__[6] * s5 * c1
    s6 = s6_ / c1
    r6 = __constants__[7] * s6 * c1
    
    #__p__.x[1] .= [c1,]
    __du__ .= [
      -r1,  # ds1_/dt
      -r2,  # ds2_/dt
      -r3,  # ds3_/dt
      -r4,  # ds4_/dt
      -r5,  # ds5_/dt
      -r6,  # ds6_/dt
    ]
end

### output function
# XXX: currently force amounts: s1_, s2_ are not supported
function nameless_saving_generator_(__outputIds__::Vector{Symbol})
    __wrongIds__ = setdiff(__outputIds__, [:c1,:s1,:r1,:s2,:r2,:s3,:r3,:s4,:r4,:s5,:r5,:s6,:r6,])
    !isempty(__wrongIds__) && throw("The following observables have not been found in the model's Records: $(__wrongIds__)")

    __out_expr__ = Expr(:block)
    [push!(__out_expr__.args, :(__out__[$i] = $obs)) for (i,obs) in enumerate(__outputIds__)]

    @eval function(__out__, __u__, t, __integrator__)
        (c1,) = __integrator__.p.x[1]
        __constants__ = __integrator__.p.x[2]
        (s1_,s2_,s3_,s4_,s5_,s6_,) = __u__

        # Heta rules
        s1 = s1_ / c1
        r1 = __constants__[2] * s1 * c1
        s2 = s2_ / c1
        r2 = __constants__[3] * s2 * c1
        s3 = s3_ / c1
        r3 = __constants__[4] * s3 * c1
        s4 = s4_ / c1
        r4 = __constants__[5] * s4 * c1
        s5 = s5_ / c1
        r5 = __constants__[6] * s5 * c1
        s6 = s6_ / c1
        r6 = __constants__[7] * s6 * c1
        
        # force amount

        $(__out_expr__)
        return nothing
    end
end

### TIME EVENTS ###
function nameless_sw1_tstops_func_(__constants__, __times__)
    return 12.0 > 0.0 ? collect(range(0.0, __times__[2]; step=12.0)) : [0.0]
end
function nameless_sw2_tstops_func_(__constants__, __times__)
    return 12.0 > 0.0 ? collect(range(1.0, __times__[2]; step=12.0)) : [1.0]
end

### D EVENTS ###
function nameless_sw5_condition_func_(__u__, t, __integrator__)
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __u__

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    r4 = __constants__[5] * s4 * c1
    s5 = s5_ / c1
    
    return s5 < __constants__[1]
end
function nameless_sw6_condition_func_(__u__, t, __integrator__)
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __u__

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    r4 = __constants__[5] * s4 * c1
    s5 = s5_ / c1
    r5 = __constants__[6] * s5 * c1
    s6 = s6_ / c1
    
    return s6 < __constants__[1]
end

### C EVENTS ###
function nameless_sw3_condition_func_(__u__, t, __integrator__)
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __u__

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    
    return __constants__[1] - s3
end
function nameless_sw4_condition_func_(__u__, t, __integrator__)
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __u__

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    
    return __constants__[1] - s4
end

### STOP EVENTS ###

### event assignments
function nameless_sw1_affect_func_(__integrator__)
    t = __integrator__.t
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __integrator__.u

    # Heta rules
    s1 = s1_ / c1
    
    # recalculated values
    (s1,) = (s1 + 1e+0 / c1,)
    
    # save results
    __integrator__.u[[1,]] = [
        s1*c1,
    ]
    __integrator__.p[[]] = [
    ]
end
function nameless_sw2_affect_func_(__integrator__)
    t = __integrator__.t
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __integrator__.u

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    
    # recalculated values
    (s2,) = (s2 + 1e+0 / c1,)
    
    # save results
    __integrator__.u[[2,]] = [
        s2*c1,
    ]
    __integrator__.p[[]] = [
    ]
end
function nameless_sw3_affect_func_(__integrator__)
    t = __integrator__.t
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __integrator__.u

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    
    # recalculated values
    (s3,) = (s3 + 1e+0 / c1,)
    
    # save results
    __integrator__.u[[3,]] = [
        s3*c1,
    ]
    __integrator__.p[[]] = [
    ]
end
function nameless_sw4_affect_func_(__integrator__)
    t = __integrator__.t
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __integrator__.u

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    
    # recalculated values
    (s4,) = (s4 + 1e+0 / c1,)
    
    # save results
    __integrator__.u[[4,]] = [
        s4*c1,
    ]
    __integrator__.p[[]] = [
    ]
end
function nameless_sw5_affect_func_(__integrator__)
    t = __integrator__.t
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __integrator__.u

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    r4 = __constants__[5] * s4 * c1
    s5 = s5_ / c1
    
    # recalculated values
    (s5,) = (s5 + 1e+0 / c1,)
    
    # save results
    __integrator__.u[[5,]] = [
        s5*c1,
    ]
    __integrator__.p[[]] = [
    ]
end
function nameless_sw6_affect_func_(__integrator__)
    t = __integrator__.t
    (c1,) = __integrator__.p.x[1]
    __constants__ = __integrator__.p.x[2]
    (s1_,s2_,s3_,s4_,s5_,s6_,) = __integrator__.u

    # Heta rules
    s1 = s1_ / c1
    r1 = __constants__[2] * s1 * c1
    s2 = s2_ / c1
    r2 = __constants__[3] * s2 * c1
    s3 = s3_ / c1
    r3 = __constants__[4] * s3 * c1
    s4 = s4_ / c1
    r4 = __constants__[5] * s4 * c1
    s5 = s5_ / c1
    r5 = __constants__[6] * s5 * c1
    s6 = s6_ / c1
    
    # recalculated values
    (s6,) = (s6 + 1e+0 / c1,)
    
    # save results
    __integrator__.u[[6,]] = [
        s6*c1,
    ]
    __integrator__.p[[]] = [
    ]
end


### MODELS ###

nameless_model_ = (
  nameless_init_func_!,
  nameless_ode_func_,
  NamedTuple{(
    :sw1,
    :sw2,
  )}([
    (nameless_sw1_tstops_func_, nameless_sw1_affect_func_, true), 
    (nameless_sw2_tstops_func_, nameless_sw2_affect_func_, true), 
  ]),
  NamedTuple{(
    :sw5,
    :sw6,
  )}([
    (nameless_sw5_condition_func_, nameless_sw5_affect_func_, true),
    (nameless_sw6_condition_func_, nameless_sw6_affect_func_, false),
  ]),
  NamedTuple{(
    :sw3,
    :sw4,
  )}([
    (nameless_sw3_condition_func_, nameless_sw3_affect_func_, true),
    (nameless_sw4_condition_func_, nameless_sw4_affect_func_, true),
  ]),
  NamedTuple{(
  )}([
  ]),
  nameless_saving_generator_,
  nameless_constants_num_,
  nameless_statics_id_,
  nameless_events_active_,
  nameless_records_output_,
  nameless_dynamic_nonss_
)

### OUTPUT ###

return (
  (
    nameless = nameless_model_,
  ),
  (),
  "0.11.1"
)

end
)()