#= 
    This code was generated by heta-compiler 0.12.1
=#

(function()

### create default constants
nameless_constants_num_ = NamedTuple{(
  :k1,
)}(Float64[
  0.001,
])
### create static ids
nameless_statics_id_ = (
    :comp1,
)

### create default observables
nameless_records_output_ = NamedTuple{(
  :comp1,:s1,:s2,:r1,
)}(Bool[
  false,true,true,true,
])

### create default events
nameless_events_active_ = NamedTuple{(
  
)}(Bool[
  
])

### vector of non-steady-state
nameless_dynamic_nonss_ = NamedTuple{(
  :s1,:s2,
)}(Bool[
  true,true,
])

### initialization of ODE variables and Records
function nameless_init_func_!(__u0__, __p0__, __constants__)
    # Heta initialize
    t = 0.0 # initial time
    s2 = 0e+0
    s1 = 1.2e+1
    comp1 = 1.5
    r1 = __constants__[1] * s1 * comp1
    
    # save results
    __u0__ .= (
        s1 * comp1,
        s2 * comp1,
    )

    __p0__ .= (
        comp1,
    )

    return nothing
end

### calculate RHS of ODE
function nameless_ode_func_(__du__, __u__, __p__, t)
    (comp1,) = __p__.x[1]
    __constants__ = __p__.x[2]
    (s1_,s2_,) = __u__ 

    # Heta rules
    s2 = s2_ / comp1
    s1 = s1_ / comp1
    r1 = __constants__[1] * s1 * comp1
    
    #__p__.x[1] .= [comp1,]
    __du__ .= [
      -r1,  # ds1_/dt
      r1,  # ds2_/dt
    ]
end

### output function
# XXX: currently force amounts: s1_, s2_ are not supported
function nameless_saving_generator_(__outputIds__::Vector{Symbol})
    __wrongIds__ = setdiff(__outputIds__, [:comp1,:s1,:s2,:r1,])
    !isempty(__wrongIds__) && throw("The following observables have not been found in the model's Records: $(__wrongIds__)")

    __out_expr__ = Expr(:block)
    [push!(__out_expr__.args, :(__out__[$i] = $obs)) for (i,obs) in enumerate(__outputIds__)]

    @eval function(__out__, __u__, t, __integrator__)
        (comp1,) = __integrator__.p.x[1]
        __constants__ = __integrator__.p.x[2]
        (s1_,s2_,) = __u__

        # Heta rules
        s2 = s2_ / comp1
        s1 = s1_ / comp1
        r1 = __constants__[1] * s1 * comp1
        
        # force amount

        $(__out_expr__)
        return nothing
    end
end

### TIME EVENTS ###

### D EVENTS ###

### C EVENTS ###

### STOP EVENTS ###

### event assignments


### MODELS ###

nameless_model_ = (
  nameless_init_func_!,
  nameless_ode_func_,
  NamedTuple{(
  )}([
  ]),
  NamedTuple{(
  )}([
  ]),
  NamedTuple{(
  )}([
  ]),
  NamedTuple{(
  )}([
  ]),
  nameless_saving_generator_,
  nameless_constants_num_,
  nameless_statics_id_,
  nameless_events_active_,
  nameless_records_output_,
  nameless_dynamic_nonss_
)

### OUTPUT ###

return (
  (
    nameless = nameless_model_,
  ),
  (),
  "0.12.1"
)

end
)()