#= 
    This code was generated by heta-compiler 
=#

function get_MTKmodel()

### Define independent and dependent variables ###

@variables t
__ruleVariables__ = @variables a0(t) s1(t) s2(t) vabs(t) vel(t)
__dynamicVariables__ = @variables _a0_(t) _s1_(t)

### Define potential algebraic variables ###

### Define parameters (constants and statics) ###
__constParameters__ = @parameters kabs kel sw2_start
__staticParameters__ = @parameters _s2_ comp0 comp1

### Define an operator for the differentiation w.r.t. time
__D__ = Differential(t)

### ODE Equations ###
__eqs__ = [
  # extended rules
  a0 ~ _a0_,
  s1 ~ _s1_/ comp1,
  s2 ~ _s2_/ comp1,
  vabs ~ kabs * a0,
  vel ~ kel * s1 * comp1,

  # ODEs
  __D__(_a0_) ~ -vabs, # da0/dt
  __D__(_s1_) ~ vabs-vel, # ds1/dt
]

### TIME EVENTS ###
#=
function __sw0_tstops__(__constants__, __times__)
    return [40.0]
end

function __sw1_tstops__(__constants__, __times__)
    return 12.0 > 0.0 ? collect(range(0.0, 60.0; step=12.0)) : [0.0]
end

function __sw2_tstops__(__constants__, __times__)
  return 24.0 > 0.0 ? collect(range(__constants__[3], __times__[2]; step=24.0)) : [__constants__[3]]
end
=#
__sw0_tstops__ = (t == [40.])
__sw1_tstops__ = (t in collect(range(0.0, 60.0; step=12.0)))
__sw2_tstops__ = (t in collect(range(sw2_start, 100.; step=24.0)))



### C EVENTS ###

### STOP EVENTS ###

### EVENTS ASSIGNMENTS ###
__sw0_affect__ = [
]
__sw1_affect__ = [
    _a0_ ~ (a0 + 1e+1),
    comp1 ~ 6e+0,
]
__sw2_affect__ = [
    _s1_ ~ (s1 + 2e+0) * comp1,
    _s2_ ~ (s2 + 2e+0) * comp1,
]


### Initialization ###

__constValues__ = [
  kabs => 0.01,
  kel => 0.01,
  sw2_start => 5,
]

__init__ = [
  a0 => 0e+0,
  s1 => 0e+0,
  s2 => 0e+0,
  comp0 => 1e+0,
  comp1 => 5.2,
  vabs => kabs * a0,
  vel => kel * s1 * comp1,
]

__amountsInit__ = [
    _a0_ => a0,
    _s1_ => s1 * comp1,
    _s2_ => s2 * comp1,
]

### ODESystem definition ###
__sys__ = ODESystem(__eqs__, t, [__dynamicVariables__; __ruleVariables__], [__constParameters__; __staticParameters__],
  name = :nameless,
  discrete_events = [__sw0_tstops__=>__sw0_affect__, __sw1_tstops__=>__sw1_affect__, __sw2_tstops__=>__sw2_affect__],
  defaults = [__constValues__; __init__; __amountsInit__]
)

return (
  structural_simplify(__sys__),
  __amountsInit__,
  __constValues__
)

end # function __get_nameless_model__

__model__ = get_MTKmodel()