[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "e530e6e50018fedbd2794d38962bf2f24175b549"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "9554fd987cbebfb6931146d405f4bbd2fa83bbfa54a734e3a7132ca2097f5f37"
    url = "https://github.com/hetalang/heta-compiler/releases/download/julia_test/heta-compiler-linux-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "f34543c21e5ad720160846bb20f0f781c24639a4"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "757f49e33b2374b2860f64ff5b2c84a4db79868060028ec5cd64a2d6a0604db2"
    url = "https://github.com/hetalang/heta-compiler/releases/download/julia_test/heta-compiler-linux-arm64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "15a782eb9031844464595a7be6b322562800e639"
os = "windows"

    [[heta_app.download]]
    sha256 = "b456fad956a49e344da76ed9205039f188657a7080794494504263b085d255ec"
    url = "https://github.com/hetalang/heta-compiler/releases/download/julia_test/heta-compiler-windows-x64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "d725ada463c13af8ced3e5a3a572674c0270be7a"
os = "macos"

    [[heta_app.download]]
    sha256 = "65064ad1a7862ccd3c98c57c1209dc1149714f3cd5acc45940d6bebf6f917bd4"
    url = "https://github.com/hetalang/heta-compiler/releases/download/julia_test/heta-compiler-macos-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "0c247da01e1af1de0a8a986737cd41201d7b4d17"
os = "macos"

    [[heta_app.download]]
    sha256 = "556a82bd878d32da3f743284b99f8d9d5160d6ab2acad982581ff7e1343f7e8f"
    url = "https://github.com/hetalang/heta-compiler/releases/download/julia_test/heta-compiler-macos-arm64.tar.gz"
