[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "a23558d3a8dafc1280df998cda01be5f3df5322b"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "c3de7b6935653e4f0e4b0ff7251b639e76d5fecda1a825784f72ee02cb2381c5"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.8.7/heta-compiler-linux.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "b31deea146ed62c2f686888074499a99fb876080"
os = "windows"

    [[heta_app.download]]
    sha256 = "0b8af8715f6a50240dd475599615c466c4d4bd7979477a512c0b8de20d6cacdf"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.8.7/heta-compiler-windows.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "a741cebf5cd6872b9da78a1713e5b835f9bc919b"
os = "macos"

    [[heta_app.download]]
    sha256 = "9454cd0b5a47f5692a5a5decdf47a0e03ef18892f4be5c55d28777bf499176a3"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.8.7/heta-compiler-macos.tar.gz"
