[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "7a83040d485316c22ecef2b664b35a33aa440bd5"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "f9f048ea9485de1fdea25da994af467acb791a81905f96f543158c0954265bda"
    url = "https://github.com/hetalang/heta-compiler/releases/download/0.9.1/heta-compiler-linux.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "b9db1bbb1880eff0e7fb132fb8667b6a49329ec1"
os = "windows"

    [[heta_app.download]]
    sha256 = "51886e6dc13675f5e9c388195677f50f16276e196201799bdcb2765f8b07e425"
    url = "https://github.com/hetalang/heta-compiler/releases/download/0.9.1/heta-compiler-windows.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "e7da3b902999a5324eb13d6c1c4ee2cf5308a956"
os = "macos"

    [[heta_app.download]]
    sha256 = "b6afac6febab1536224e9abcead7f7b31ddd14061e8135f3cbfc0212b326fcd3"
    url = "https://github.com/hetalang/heta-compiler/releases/download/0.9.1/heta-compiler-macos.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "e7da3b902999a5324eb13d6c1c4ee2cf5308a956"
os = "macos"

    [[heta_app.download]]
    sha256 = "b6afac6febab1536224e9abcead7f7b31ddd14061e8135f3cbfc0212b326fcd3"
    url = "https://github.com/hetalang/heta-compiler/releases/download/0.9.1/heta-compiler-macos.tar.gz"
