[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "7f561aa65b663cbd121aacdc41dbc24160df2f84"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "4883f831dabc2f1ed78234fa61a7cc980ca61744055b893fa3da77714252303a"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.8.6/heta-compiler-linux.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "93c1330a1dce7f8aa62214c0cb5e612c02187956"
os = "windows"

    [[heta_app.download]]
    sha256 = "a0611f5ca671bd67edda6fbb062322ca89dbe2f4f0852ea8db30788f43c789c7"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.8.6/heta-compiler-windows.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "403687ab7168c0a246610d1bb6513d3cb1e5d549"
os = "macos"

    [[heta_app.download]]
    sha256 = "5381c78d522bd550991265f37b7699387c85bb1af49eb08c313a8b9abb732335"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.8.6/heta-compiler-macos.tar.gz"
