[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "f6c4aa1d62c3528a9de122c9345fab541781fdc3"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "43da39c03bd9454ce8b3e4224c63f1e1993008b57029527dff792c34f499cf25"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.0/heta-compiler-linux-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "280e99c2de6939bf7da9565d78b9679fa339676e"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "38f604a416fbf71428eeb44699388719b574c4bdb58fb33f5dc1d4476cf522e1"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.0/heta-compiler-linux-arm64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "b135b7848547d2bb4fe27b576e8364c9900d0bb2"
os = "windows"

    [[heta_app.download]]
    sha256 = "3cd694fb2c73f36f0603d55875954f8a6403fc4ad2103f6db177e50295ff0302"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.0/heta-compiler-windows-x64.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "9496b6efa6a40db07a975fa4e39cdb7a7adc0908"
os = "macos"

    [[heta_app.download]]
    sha256 = "8ea4bab6bc953e030798a400c9ce9a89f43f69f8a47b0bc6830183a38b6bc248"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.0/heta-compiler-macos-x64.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "4963a8248bf3be56d7cd7526ae262635dedbfaaf"
os = "macos"

    [[heta_app.download]]
    sha256 = "25836da5185337a329a6764454f392566a77a3e5f2c1e8728d3df4f764af3d73"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.12.0/heta-compiler-macos-arm64.tar.gz"
