[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "ab9376e9291f631fe099983ef088d36b1d667305"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "6b2a29ba8d82390f79cb5d8f88482ffc83f27b89c73aef16e053015aec5da94b"
    url = "https://github.com/hetalang/heta-compiler/releases/download/draft-tswitcher/heta-compiler-linux.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "f6a25bd7e2fbe296daff9724581bfe5ba42fed6d"
os = "windows"

    [[heta_app.download]]
    sha256 = "0748d24c6b0ba5923915717ad3bd5058e189026b54b455780e63e1d7bbc61152"
    url = "https://github.com/hetalang/heta-compiler/releases/download/draft-tswitcher/heta-compiler-windows.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "24ec3692913611b2691d62334ff87eca26cb9dce"
os = "macos"

    [[heta_app.download]]
    sha256 = "0e83043a6e8c5e2382dab2bc3550c08305141fb5ed0e1adfa0926f8be7c759ec"
    url = "https://github.com/hetalang/heta-compiler/releases/download/draft-tswitcher/heta-compiler-macos.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "24ec3692913611b2691d62334ff87eca26cb9dce"
os = "macos"

    [[heta_app.download]]
    sha256 = "0e83043a6e8c5e2382dab2bc3550c08305141fb5ed0e1adfa0926f8be7c759ec"
    url = "https://github.com/hetalang/heta-compiler/releases/download/draft-tswitcher/heta-compiler-macos.tar.gz"
