[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "3555032f7d9bf3667af7c796e7c5e6ef65ab184d"
libc = "glibc"
os = "linux"

    [[heta_app.download]]
    sha256 = "93b951ccf358cdd06f525a6022d1fae801d9e135f7196d082bc1b1ff44069058"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.9.0/heta-compiler-linux.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "f9a91d0fab917fbd4567bd9c1330670483f77431"
os = "windows"

    [[heta_app.download]]
    sha256 = "950b729cf15a60ab83bd3997b9cc0424f0f8885b311d319690052093c9bc2ef6"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.9.0/heta-compiler-windows.tar.gz"
[[heta_app]]
arch = "x86_64"
git-tree-sha1 = "0da38cac8b6fbf9d7d20316a2b1c0e6dc1b4adc3"
os = "macos"

    [[heta_app.download]]
    sha256 = "8cb8bf7d3fe70926726074debd3692ac641903623669e3d0930552eb2c8ed8be"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.9.0/heta-compiler-macos.tar.gz"
[[heta_app]]
arch = "aarch64"
git-tree-sha1 = "0da38cac8b6fbf9d7d20316a2b1c0e6dc1b4adc3"
os = "macos"

    [[heta_app.download]]
    sha256 = "8cb8bf7d3fe70926726074debd3692ac641903623669e3d0930552eb2c8ed8be"
    url = "https://github.com/hetalang/heta-compiler/releases/download/v0.9.0/heta-compiler-macos.tar.gz"
