name: DockerIMG
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  DockerIMG:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - run: julia --project -e 'import Pkg; Pkg.add(string(:SimpleContainerGenerator)); import SimpleContainerGenerator; pkgs = [(name = "HetaSimulator",url="https://github.com/hetalang/HetaSimulator.jl"),];  SimpleContainerGenerator.create_dockerfile(pkgs;no_test=["HetaSimulator"], julia_version = v"1.6.0")'
      - if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'schedule')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t dilumaluthge/predictmd .
      - run: docker run insysbio/hetasimulator "JULIA_DEBUG=all /usr/bin/julia -e 'import Pkg; Pkg.test(string(:HetaSimulator))'"
      - if: success() && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'schedule')
        run: docker push insysbio/hetasimulator