name: Docker QSP Platforms Builder
on:
  workflow_run:
    workflows: ["TagBot"]
    types: 
      - completed
  workflow_dispatch:
jobs:
  DockerIMG:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push qsp-platforms-builder
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./dockerfiles/qsp-platforms-builder/Dockerfile
        tags: ${{ secrets.DOCKER_USERNAME }}/qsp-platforms-builder:latest